# Generated by Django 3.1.4 on 2021-06-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_download', '0002_auto_20210609_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downkey',
            name='owner',
        ),
    ]
