# Generated by Django 3.1.4 on 2021-06-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_download', '0003_remove_downkey_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downkey',
            name='sec_key',
            field=models.CharField(max_length=100),
        ),
    ]
