# Generated by Django 3.1.4 on 2021-06-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='office',
            field=models.CharField(choices=[('0', '*ALL'), ('1', 'New York'), ('2', 'Los Angeles')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=20, verbose_name='fileename'),
        ),
    ]
