# Generated by Django 3.1.4 on 2021-06-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_auto_20210609_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='office',
        ),
        migrations.AddField(
            model_name='file',
            name='allow',
            field=models.ManyToManyField(to='file_upload.active'),
        ),
    ]
