# Generated by Django 3.1.4 on 2021-06-09 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_upload', '0003_auto_20210609_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='allow',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
