# Generated by Django 3.1.4 on 2021-06-12 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_upload', '0004_auto_20210609_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='allow',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=20, verbose_name='filename'),
        ),
    ]
